### PR TITLE
Add simple bin script

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/mulesoft/api-designer/issues/315

We could also add a little bit of code to open the users browser automatically in the future.

### CODE REVIEW

**Comment by sichvoge** [comment]
So currently it is starting the process and you manually have to open you browser and go to the API Designer URL?

**Comment by blakeembrey** [comment]
@sichvoge Yes, hence the suggestion. It currently logs the URL out to the screen but it's a pretty simple change to open the users browser. It's just a matter of UX.

**Comment by sichvoge** [comment]
IMHO, if that is simple to implement please add it!

**Comment by blakeembrey** [comment]
@sichvoge Added `open` and some instructions on the README.

**Pull request merged**
