### PR TITLE
Fix protractor tests, commenting the ones that are failing

### PR DESCRIPTION
**Pull request by juancoen**
- Run tests with Chrome Web Driver as it works better.
- Fix an issue in tests initialization.
- Commented failing tests and added a TODO to each one of them.

### CODE REVIEW

**Comment by juancoen** [comment]
@sichvoge @blakeembrey can you guys check this pull? Thanks!

**Comment by blakeembrey** [comment]
LGTM :+1: Any reason for the browser change?

**Comment by sichvoge** [comment]
Yes, that's something I wonder as well!

**Comment by juancoen** [comment]
I changed it because FF is not working with the selenium-webdriver version currently installed in the project. I tried updating devDependencies but that broke more things. That update must be done, but in a different PR.

I've done a little research and it seems that selenium-webdriver usually fails with new FF versions, so I think it's better to use Chrome as it works more consistently.

**Comment by sichvoge** [comment]
Sounds good - leave the rest to @blakeembrey and @dmartinezg

**Comment by juancoen** [comment]
@blakeembrey can I merge this?

**Comment by blakeembrey** [comment]
@juancoen Yes, looks good to me.

**Pull request merged**
