### PR TITLE
Maintain CodeMirror document with each file

### LINKED ISSUE #220: ctrl+z with multiple files mixes files' content
Scenario:
Having 2 files in the designer (both saved) do this:
  - add something to the file A.
  - save file A.
  - go to file B.
  - press ctrl+z.
  
  -> You will get the data of the file A overriding file B, and losing the data in file B.

### PR DESCRIPTION
**Pull request by blakeembrey**
Fixes #220. CodeMirror documents hold all editor information, such as value, history and cursor positions.

### CODE REVIEW

**Comment by sichvoge** [comment]
@dmartinezg can you please give a quick shout and a thumbs up for that :+1:

**Comment by dmartinezg** [comment]
@alejandroschenzle, can you dedicate some time to look into this?

My concern is any other event not being handled.

**Comment by juancoen** [comment]
@blakeembrey I've fixed a minor bug in your solution and added a test. Your fix looks good to me.

@dmartinezg Can you explain your concern? Which are the other events you are concerned about? Thanks!

**Comment by juancoen** [comment]
I've been testing this fix for some time now. Everything seems to be working well.
I've only found this bug but it can be reproduced in master: https://github.com/mulesoft/api-designer/issues/342

good work @blakeembrey, merging!

**Pull request merged**
